// 2026 Masters Tournament Field — Official invitees
// Source: masters.com, PGA Tour, DraftKings odds (as of April 2, 2026)
// Withdrawn players are stored in MASTERS_WITHDRAWN_2026 and excluded from the draw.
// They can be moved back to active for future tournaments.
// Groups will be assigned dynamically based on participant count

import { MASTERS_HISTORY } from './mastersHistoryData';

const RAW_FIELD = [
  { name: 'Scottie Scheffler', betting_odds: '+350', world_ranking: 1 },
  { name: 'Rory McIlroy', betting_odds: '+700', world_ranking: 2 },
  { name: 'Jon Rahm', betting_odds: '+1000', world_ranking: 3 },
  { name: 'Bryson DeChambeau', betting_odds: '+1000', world_ranking: 4 },
  { name: 'Xander Schauffele', betting_odds: '+1800', world_ranking: 5 },
  { name: 'Ludvig Åberg', betting_odds: '+1600', world_ranking: 6 },
  { name: 'Collin Morikawa', betting_odds: '+2200', world_ranking: 7 },
  { name: 'Hideki Matsuyama', betting_odds: '+3500', world_ranking: 8 },
  { name: 'Patrick Cantlay', betting_odds: '+2500', world_ranking: 9 },
  { name: 'Viktor Hovland', betting_odds: '+3000', world_ranking: 10 },
  { name: 'Tommy Fleetwood', betting_odds: '+3000', world_ranking: 11 },
  { name: 'Shane Lowry', betting_odds: '+3500', world_ranking: 12 },
  { name: 'Robert MacIntyre', betting_odds: '+3500', world_ranking: 13 },
  { name: 'Russell Henley', betting_odds: '+4000', world_ranking: 14 },
  { name: 'Matt Fitzpatrick', betting_odds: '+3000', world_ranking: 15 },
  { name: 'Sahith Theegala', betting_odds: '+4000', world_ranking: 16 },
  { name: 'Sungjae Im', betting_odds: '+4000', world_ranking: 17 },
  { name: 'Patrick Reed', betting_odds: '+3000', world_ranking: 18 },
  { name: 'Brian Harman', betting_odds: '+4000', world_ranking: 19 },
  { name: 'Keegan Bradley', betting_odds: '+4000', world_ranking: 20 },
  { name: 'Justin Thomas', betting_odds: '+3500', world_ranking: 21 },
  { name: 'Jordan Spieth', betting_odds: '+4000', world_ranking: 22 },
  { name: 'Brooks Koepka', betting_odds: '+4500', world_ranking: 23 },
  { name: 'Sam Burns', betting_odds: '+5000', world_ranking: 24 },
  { name: 'Cameron Young', betting_odds: '+4000', world_ranking: 25 },
  { name: 'Tony Finau', betting_odds: '+5000', world_ranking: 26 },
  { name: 'Corey Conners', betting_odds: '+5000', world_ranking: 27 },
  { name: 'Justin Rose', betting_odds: '+5000', world_ranking: 28 },
  { name: 'Tom Kim', betting_odds: '+5000', world_ranking: 29 },
  { name: 'Min Woo Lee', betting_odds: '+5000', world_ranking: 30 },
  { name: 'Aaron Rai', betting_odds: '+5000', world_ranking: 31 },
  { name: 'Wyndham Clark', betting_odds: '+8000', world_ranking: 32 },
  { name: 'Max Homa', betting_odds: '+5000', world_ranking: 33 },
  { name: 'Sepp Straka', betting_odds: '+6000', world_ranking: 34 },
  { name: 'Cameron Smith', betting_odds: '+6600', world_ranking: 35 },
  { name: 'Adam Scott', betting_odds: '+6600', world_ranking: 36 },
  { name: 'Jason Day', betting_odds: '+7000', world_ranking: 37 },
  { name: 'Si Woo Kim', betting_odds: '+7000', world_ranking: 38 },
  { name: 'Akshay Bhatia', betting_odds: '+5000', world_ranking: 39 },
  { name: 'Chris Kirk', betting_odds: '+7000', world_ranking: 40 },
  { name: 'Tyrrell Hatton', betting_odds: '+4500', world_ranking: 41 },
  { name: 'Nick Taylor', betting_odds: '+8000', world_ranking: 42 },
  { name: 'Harris English', betting_odds: '+7000', world_ranking: 43 },
  { name: 'Daniel Berger', betting_odds: '+6000', world_ranking: 44 },
  { name: 'Billy Horschel', betting_odds: '+8000', world_ranking: 45 },
  { name: 'Davis Thompson', betting_odds: '+6000', world_ranking: 46 },
  { name: 'Maverick McNealy', betting_odds: '+6000', world_ranking: 47 },
  { name: 'Chris Gotterup', betting_odds: '+4500', world_ranking: 48 },
  { name: 'Kurt Kitayama', betting_odds: '+7000', world_ranking: 49 },
  { name: 'Ben Griffin', betting_odds: '+7000', world_ranking: 50 },
  { name: 'Nicolai Hojgaard', betting_odds: '+5000', world_ranking: 51 },
  { name: 'Ryan Fox', betting_odds: '+6000', world_ranking: 52 },
  { name: 'J.J. Spaun', betting_odds: '+9000', world_ranking: 53 },
  { name: 'Jacob Bridgeman', betting_odds: '+8000', world_ranking: 54 },
  { name: 'Joaquín Niemann', betting_odds: '+5000', world_ranking: 55 },
  { name: 'Dustin Johnson', betting_odds: '+9000', world_ranking: 56 },
  { name: 'Michael Brennan', betting_odds: '+8000', world_ranking: 57 },
  { name: 'Denny McCarthy', betting_odds: '+8000', world_ranking: 58 },
  { name: 'Andrew Novak', betting_odds: '+9000', world_ranking: 59 },
  { name: 'Ryan Gerard', betting_odds: '+9000', world_ranking: 60 },
  { name: 'Alex Noren', betting_odds: '+10000', world_ranking: 61 },
  { name: 'Kristoffer Reitan', betting_odds: '+10000', world_ranking: 62 },
  { name: 'Sam Stevens', betting_odds: '+10000', world_ranking: 63 },
  { name: 'Max Greyserman', betting_odds: '+8000', world_ranking: 64 },
  { name: 'Nick Dunlap', betting_odds: '+7000', world_ranking: 65 },
  { name: 'Rasmus Hojgaard', betting_odds: '+8000', world_ranking: 66 },
  { name: 'Harry Hall', betting_odds: '+10000', world_ranking: 67 },
  { name: 'Sergio Garcia', betting_odds: '+10000', world_ranking: 68 },
  { name: 'Phil Mickelson', betting_odds: '+20000', world_ranking: 69 },
  { name: 'Nico Echavarria', betting_odds: '+10000', world_ranking: 70 },
  { name: 'Marco Penge', betting_odds: '+15000', world_ranking: 71 },
  { name: 'Carlos Ortiz', betting_odds: '+15000', world_ranking: 72 },
  { name: 'Davis Riley', betting_odds: '+10000', world_ranking: 73 },
  { name: 'Aldrich Potgieter', betting_odds: '+12000', world_ranking: 74 },
  { name: 'Sami Valimaki', betting_odds: '+12000', world_ranking: 75 },
  { name: 'Brian Campbell', betting_odds: '+15000', world_ranking: 76 },
  { name: 'Naoyuki Kataoka', betting_odds: '+20000', world_ranking: 77 },
  { name: 'Tom McKibbin', betting_odds: '+10000', world_ranking: 78 },
  { name: 'Casey Jarvis', betting_odds: '+20000', world_ranking: 79 },
  { name: 'Rasmus Neergaard-Petersen', betting_odds: '+15000', world_ranking: 80 },
  { name: 'Matt McCarty', betting_odds: '+12000', world_ranking: 81 },
  { name: 'Jake Knapp', betting_odds: '+8000', world_ranking: 82 },
  { name: 'Johnny Keefer', betting_odds: '+15000', world_ranking: 83 },
  { name: 'Michael Kim', betting_odds: '+15000', world_ranking: 84 },
  { name: 'Haotong Li', betting_odds: '+15000', world_ranking: 85 },
  { name: 'Bubba Watson', betting_odds: '+25000', world_ranking: 86 },
  { name: 'Charl Schwartzel', betting_odds: '+35000', world_ranking: 87 },
  { name: 'Zach Johnson', betting_odds: '+40000', world_ranking: 88 },
  { name: 'Danny Willett', betting_odds: '+50000', world_ranking: 89 },
];

const RAW_WITHDRAWN = [
  { name: 'Tiger Woods', betting_odds: 'N/A', world_ranking: null, status: 'withdrawn', note: 'Not competing in 2026 - recovery' },
  { name: 'Ángel Cabrera', betting_odds: 'N/A', world_ranking: null, status: 'withdrawn', note: 'Not competing' },
  { name: 'Fred Couples', betting_odds: 'N/A', world_ranking: null, status: 'withdrawn', note: 'Past champion - not competing' },
  { name: 'Vijay Singh', betting_odds: 'N/A', world_ranking: null, status: 'withdrawn', note: 'Past champion - not competing' },
  { name: 'Mike Weir', betting_odds: 'N/A', world_ranking: null, status: 'withdrawn', note: 'Past champion - not competing' },
  { name: 'José María Olazábal', betting_odds: 'N/A', world_ranking: null, status: 'withdrawn', note: 'Past champion - not competing' },
  { name: 'Gary Woodland', betting_odds: 'N/A', world_ranking: null, status: 'withdrawn', note: 'Medical - not competing' },
];

// Active field with history merged
export const MASTERS_FIELD_2026 = RAW_FIELD.map(g => ({
  ...g,
  masters_history: MASTERS_HISTORY[g.name] || null,
}));

// Withdrawn players with history merged
export const MASTERS_WITHDRAWN_2026 = RAW_WITHDRAWN.map(g => ({
  ...g,
  masters_history: MASTERS_HISTORY[g.name] || null,
}));