// 2026 Masters Tournament Field - Pre-populated with projected odds and rankings
// Groups will be assigned dynamically based on participant count

export const MASTERS_FIELD_2026 = [
  { name: 'Scottie Scheffler', betting_odds: '+400', world_ranking: 1 },
  { name: 'Ludvig Åberg', betting_odds: '+1200', world_ranking: 2 },
  { name: 'Jon Rahm', betting_odds: '+1400', world_ranking: 3 },
  { name: 'Xander Schauffele', betting_odds: '+1600', world_ranking: 4 },
  { name: 'Rory McIlroy', betting_odds: '+2000', world_ranking: 5 },
  { name: 'Victor Hovland', betting_odds: '+2200', world_ranking: 6 },
  { name: 'Hideki Matsuyama', betting_odds: '+2000', world_ranking: 7 },
  { name: 'Patrick Cantlay', betting_odds: '+2500', world_ranking: 8 },
  { name: 'Brian Harman', betting_odds: '+2500', world_ranking: 9 },
  { name: 'Wyndham Clark', betting_odds: '+2800', world_ranking: 10 },
  { name: 'Brooks Koepka', betting_odds: '+2800', world_ranking: 11 },
  { name: 'Collin Morikawa', betting_odds: '+2800', world_ranking: 12 },
  { name: 'Matt Fitzpatrick', betting_odds: '+3000', world_ranking: 13 },
  { name: 'Russell Henley', betting_odds: '+3000', world_ranking: 14 },
  { name: 'Tommy Fleetwood', betting_odds: '+3500', world_ranking: 15 },
  { name: 'Shane Lowry', betting_odds: '+3500', world_ranking: 16 },
  { name: 'Robert MacIntyre', betting_odds: '+3500', world_ranking: 17 },
  { name: 'Sungjae Im', betting_odds: '+3500', world_ranking: 18 },
  { name: 'Sahith Theegala', betting_odds: '+3800', world_ranking: 19 },
  { name: 'Patrick Reed', betting_odds: '+4000', world_ranking: 20 },
  { name: 'Aaron Rai', betting_odds: '+4000', world_ranking: 21 },
  { name: 'Cameron Smith', betting_odds: '+4000', world_ranking: 22 },
  { name: 'Joaquín Niemann', betting_odds: '+4200', world_ranking: 23 },
  { name: 'Max Homa', betting_odds: '+4500', world_ranking: 24 },
  { name: 'Justin Rose', betting_odds: '+4500', world_ranking: 25 },
  { name: 'Tony Finau', betting_odds: '+4500', world_ranking: 26 },
  { name: 'Daniel Berger', betting_odds: '+4800', world_ranking: 27 },
  { name: 'Sam Burns', betting_odds: '+4800', world_ranking: 28 },
  { name: 'Justin Thomas', betting_odds: '+5000', world_ranking: 29 },
  { name: 'Dustin Johnson', betting_odds: '+5000', world_ranking: 30 },
  { name: 'Keegan Bradley', betting_odds: '+5200', world_ranking: 31 },
  { name: 'Jordan Spieth', betting_odds: '+5500', world_ranking: 32 },
  { name: 'Cameron Young', betting_odds: '+5500', world_ranking: 33 },
  { name: 'Corey Conners', betting_odds: '+5500', world_ranking: 34 },
  { name: 'Min Woo Lee', betting_odds: '+5500', world_ranking: 35 },
  { name: 'Adam Scott', betting_odds: '+6000', world_ranking: 36 },
  { name: 'Tom Kim', betting_odds: '+6000', world_ranking: 37 },
  { name: 'Chris Kirk', betting_odds: '+6000', world_ranking: 38 },
  { name: 'Denny McCarthy', betting_odds: '+6500', world_ranking: 39 },
  { name: 'Jason Day', betting_odds: '+6500', world_ranking: 40 },
  { name: 'Billy Horschel', betting_odds: '+7000', world_ranking: 41 },
  { name: 'Sepp Straka', betting_odds: '+7000', world_ranking: 42 },
  { name: 'Si Woo Kim', betting_odds: '+7000', world_ranking: 43 },
  { name: 'Taylor Moore', betting_odds: '+7500', world_ranking: 44 },
  { name: 'Akshay Bhatia', betting_odds: '+7500', world_ranking: 45 },
  { name: 'Nick Dunlap', betting_odds: '+8000', world_ranking: 46 },
  { name: 'Phil Mickelson', betting_odds: '+8000', world_ranking: 47 },
  { name: 'Tiger Woods', betting_odds: '+8000', world_ranking: 48 },
  { name: 'Sergio Garcia', betting_odds: '+8500', world_ranking: 49 },
  { name: 'Tyrrell Hatton', betting_odds: '+8500', world_ranking: 50 },
  { name: 'Byeong Hun An', betting_odds: '+9000', world_ranking: 51 },
  { name: 'Davis Thompson', betting_odds: '+9000', world_ranking: 52 },
  { name: 'Stephan Jaeger', betting_odds: '+9500', world_ranking: 53 },
  { name: 'Erik van Rooyen', betting_odds: '+10000', world_ranking: 54 },
  { name: 'Luke List', betting_odds: '+10000', world_ranking: 55 },
  { name: 'Taylor Pendrith', betting_odds: '+10000', world_ranking: 56 },
  { name: 'J.T. Poston', betting_odds: '+10000', world_ranking: 57 },
  { name: 'Nick Taylor', betting_odds: '+11000', world_ranking: 58 },
  { name: 'Kevin Yu', betting_odds: '+11000', world_ranking: 59 },
  { name: 'Harris English', betting_odds: '+12000', world_ranking: 60 },
  { name: 'Lucas Glover', betting_odds: '+12000', world_ranking: 61 },
  { name: 'Mackenzie Hughes', betting_odds: '+12000', world_ranking: 62 },
  { name: 'Bubba Watson', betting_odds: '+15000', world_ranking: 63 },
  { name: 'Patrick Cantlay', betting_odds: '+15000', world_ranking: 64 },
  { name: 'Rickie Fowler', betting_odds: '+15000', world_ranking: 65 },
  { name: 'Charl Schwartzel', betting_odds: '+15000', world_ranking: 66 },
  { name: 'Webb Simpson', betting_odds: '+20000', world_ranking: 67 },
  { name: 'Zach Johnson', betting_odds: '+20000', world_ranking: 68 },
  { name: 'Danny Willett', betting_odds: '+20000', world_ranking: 69 },
  { name: 'Vijay Singh', betting_odds: '+25000', world_ranking: 70 },
  { name: 'Fred Couples', betting_odds: '+30000', world_ranking: 71 },
  { name: 'Mike Weir', betting_odds: '+30000', world_ranking: 72 },
  { name: 'Larry Mize', betting_odds: '+50000', world_ranking: 73 },
  { name: 'Jose Maria Olazabal', betting_odds: '+50000', world_ranking: 74 },
  { name: 'Bernhard Langer', betting_odds: '+50000', world_ranking: 75 },
  { name: 'Sandy Lyle', betting_odds: '+100000', world_ranking: 76 },
  { name: 'Jack Nicklaus', betting_odds: '+100000', world_ranking: 77 },
  { name: 'Gary Player', betting_odds: '+100000', world_ranking: 78 },
  { name: 'Tom Watson', betting_odds: '+100000', world_ranking: 79 },
  { name: 'Ben Crenshaw', betting_odds: '+100000', world_ranking: 80 },
];